project:
  type: website

website:
  title: "Matematik (2025-2028)"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Information"
        menu: 
          - text: "Repetition"
            href: information/ugentlig_repetition.qmd
      - text: "Projects"
        menu:
          - text: "Jacobsstav"
            href: projects/Jakobsstav_geometri/projekt.qmd
      - text: "Homework"
        menu:
          - text: "Homework 1"
            href: homework/hjemmeopg_1/hjemmeopg_1.qmd
          - text: "Homework 2"
            href: homework/hjemmeopg_2/hjemmeopg_2.qmd
      - text: "Disposition"
        menu:
          - text: "Geometri og Trigonometri"
            href: disposition/disposition1.qmd

format:
  html:
    theme: cosmo
    toc: true
